// Package swagger Code generated by nexs-swag. DO NOT EDIT
package swagger

// SwaggerDoc is the OpenAPI v3 specification in JSON format
var SwaggerDoc = `{
  "openapi": "3.1.0",
  "info": {
    "title": "Parse Internal API",
    "description": "Demonstrates --parseInternal flag",
    "version": "1.0"
  },
  "jsonSchemaDialect": "https://spec.openapis.org/oas/3.1/dialect/base",
  "servers": [
    {
      "url": "https://localhost:8080"
    }
  ],
  "paths": {
    "/internal/config": {
      "get": {
        "tags": [
          "internal"
        ],
        "summary": "Get internal config",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Config"
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get user (public)",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Config": {
        "type": "object",
        "properties": {
          "api_key": {
            "type": "string"
          },
          "secret": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}`

// ReadDoc returns the OpenAPI specification
func ReadDoc() string {
	return SwaggerDoc
}
